version: '2'
services:
  web:
    restart: always
    build:
       context: ./web
    ports:
      - "8000:8000"
    links:
      - mongodb:mongodb
      - rabbitmq:rabbit
      - redis:redis
    volumes:
      - ./web:/web
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  post_writer:
    restart: always
    build:
       context: ./post_writer
    links:
      - mongodb:mongodb
      - rabbitmq:rabbit
      - redis:redis
    volumes:
      - ./post_writer:/post_writer
    command: celery -A post_writer worker --loglevel=info

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  mongodb:
    restart: always
    image: mongo:3.2.10
    ports:
      - "27017:27017"
    volumes:
      - data:/var/data/mongodb

  rabbitmq:
    image: rabbitmq:3.6.5
    ports:
      - "5672:5672"

  redis:
    image: redis:3.2.5
    ports:
      - "6379:6379"

volumes:
  data:
    driver: local