version: '2'
services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    links:
      - mongodb
    volumes:
      - ./web:/web
#    env_file: .env
#    command: python -u app.py
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  data:
    restart: always
    image: mongo:3.2.10
    volumes:
      - /var/data

  mongodb:
    restart: always
    image: mongo:3.2.10
    ports:
      - "27017:27017"
    volumes_from:
      - data

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web