web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - mongodb
  volumes:
    - ./web:/web
  env_file: .env
  command: python -u app.py
#  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

#nginx:
#  restart: always
#  build: ./nginx/
#  ports:
#    - "80:80"
#  volumes:
#    - /www/static
#  volumes_from:
#    - web
#  links:
#    - web:web
#
#data:
#  restart: always
#  image: postgres:latest
#  volumes:
#    - /var/lib/postgresql
#  command: true

mongodb:
  restart: always
  image: mongo:3.2.10
#  volumes_from:
#    - data
  ports:
    - "7070:27017"
